server:
  port: 7777
  servlet:
    context-path: /

# jdbc
spring:
  datasource:
    url: jdbc:mysql://47.103.43.89:3306/db_book_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# jpa default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # thymeleaf config
  thymeleaf:
    cache: false
    suffix: .html
